// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerAIO.Models;

namespace SneakerAIO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210223220835_init create")]
    partial class initcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SneakerAIO.Models.SneakerModel", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("Date");

                    b.Property<string>("ShoeName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("StyleCode")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ShoeId");

                    b.ToTable("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
